

// Copyright Shunsuke Sogame 2008-2010.
// Distributed under the terms of an MIT-style license.


package com.github.okomok.mada
package dual; package nat; package dense


object AsciiLiteral {

    private  val _0B = `false`
    private type _0B = `false`

    private  val _1B = `true`
    private type _1B = `true`

     val ` `: ` ` = _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
     val  ! :  !  = _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
     val `"`: `"` = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
     val `#`: `#` = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
     val `$`: `$` = _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
     val  % :  %  = _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
     val  & :  &  = _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
     val `'`: `'` = _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
     val `(`: `(` = _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
     val `)`: `)` = _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
     val  * :  *  = _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
     val  + :  +  = _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
     val `,`: `,` = _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
     val  - :  -  = _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
     val `.`: `.` = _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val  / :  /  = _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val `0`: `0` = _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val `1`: `1` = _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val `2`: `2` = _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val `3`: `3` = _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val `4`: `4` = _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val `5`: `5` = _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val `6`: `6` = _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val `7`: `7` = _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val `8`: `8` = _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val `9`: `9` = _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val `:`: `:` = _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val `;`: `;` = _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  < :  <  = _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val `=`: `=` = _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  > :  >  = _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  ? :  ?  = _1B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
	 val  A :  A  = _1B :: _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  B :  B  = _0B :: _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  C :  C  = _1B :: _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  D :  D  = _0B :: _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  E :  E  = _1B :: _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  F :  F  = _0B :: _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  G :  G  = _1B :: _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	 val  H :  H  = _0B :: _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  I :  I  = _1B :: _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
     val  J :  J  = _0B :: _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  K :  K  = _1B :: _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  L :  L  = _0B :: _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  M :  M  = _1B :: _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  N :  N  = _0B :: _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  O :  O  = _1B :: _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	 val  P :  P  = _0B :: _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  Q :  Q  = _1B :: _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  R :  R  = _0B :: _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  S :  S  = _1B :: _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  T :  T  = _0B :: _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  U :  U  = _1B :: _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  V :  V  = _0B :: _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  W :  W  = _1B :: _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	 val  X :  X  = _0B :: _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
	 val  Y :  Y  = _1B :: _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
	 val  Z :  Z  = _0B :: _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
     val `[`: `[` = _1B :: _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
     val BSL: BSL = _0B :: _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val `]`: `]` = _1B :: _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val  ^ :  ^  = _0B :: _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val `_`: `_` = _1B :: _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
     val BQ : BQ  = _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  a :  a  = _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  b :  b  = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  c :  c  = _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  d :  d  = _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  e :  e  = _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  f :  f  = _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  g :  g  = _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
     val  h :  h  = _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  i :  i  = _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  j :  j  = _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  k :  k  = _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  l :  l  = _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  m :  m  = _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  n :  n  = _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  o :  o  = _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
     val  p :  p  = _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  q :  q  = _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  r :  r  = _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  s :  s  = _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  t :  t  = _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  u :  u  = _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  v :  v  = _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  w :  w  = _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
     val  x :  x  = _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  y :  y  = _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  z :  z  = _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val `{`: `{` = _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  | :  |  = _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
     val `}`: `}` = _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
     val  ~ :  ~  = _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil

    type ` ` = _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
    type  !  = _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
    type `"` = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
    type `#` = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
    type `$` = _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
    type  %  = _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
    type  &  = _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
    type `'` = _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
    type `(` = _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
    type `)` = _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
    type  *  = _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
    type  +  = _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
    type `,` = _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
    type  - = _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
    type `.` = _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type  /  = _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type `0` = _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type `1` = _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type `2` = _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type `3` = _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type `4` = _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type `5` = _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type `6` = _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type `7` = _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type `8` = _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type `9` = _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type `:` = _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type `;` = _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  <  = _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type `=` = _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  >  = _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  ?  = _1B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
    type `@` = _0B :: _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  A  = _1B :: _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  B  = _0B :: _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  C  = _1B :: _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  D  = _0B :: _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  E  = _1B :: _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  F  = _0B :: _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  G  = _1B :: _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: Nil
	type  H  = _0B :: _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  I  = _1B :: _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
    type  J  = _0B :: _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  K  = _1B :: _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  L  = _0B :: _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  M  = _1B :: _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  N  = _0B :: _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  O  = _1B :: _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: Nil
	type  P  = _0B :: _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  Q  = _1B :: _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  R  = _0B :: _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  S  = _1B :: _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  T  = _0B :: _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  U  = _1B :: _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  V  = _0B :: _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  W  = _1B :: _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: Nil
	type  X  = _0B :: _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
	type  Y  = _1B :: _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
	type  Z  = _0B :: _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
    type `[` = _1B :: _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: Nil
    type BSL = _0B :: _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type `]` = _1B :: _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type  ^  = _0B :: _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type `_` = _1B :: _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: Nil
    type BQ  = _0B :: _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  a  = _1B :: _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  b  = _0B :: _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  c  = _1B :: _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  d  = _0B :: _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  e  = _1B :: _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  f  = _0B :: _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  g  = _1B :: _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: Nil
    type  h  = _0B :: _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  i  = _1B :: _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  j  = _0B :: _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  k  = _1B :: _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  l  = _0B :: _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  m  = _1B :: _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  n  = _0B :: _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  o  = _1B :: _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: Nil
    type  p  = _0B :: _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  q  = _1B :: _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  r  = _0B :: _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  s  = _1B :: _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  t  = _0B :: _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  u  = _1B :: _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  v  = _0B :: _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  w  = _1B :: _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: Nil
    type  x  = _0B :: _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  y  = _1B :: _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  z  = _0B :: _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type `{` = _1B :: _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  |  = _0B :: _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
    type `}` = _1B :: _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil
    type  ~  = _0B :: _1B :: _1B :: _1B :: _1B :: _1B :: _1B :: Nil

}
