

package madatest; package defecttest; package typeerror



class MyVector[A] {
    def map[B](f: A => B): MyVector[B] = throw new Error
}

object MyVector {

    // This compiles successfully.
    def unzipOK[B, C](_this: MyVector[(B, C)]): (MyVector[B], MyVector[C]) = {
        val l = _this.map{ bc => bc._1 }
        val r = _this.map{ bc => bc._2 }
        (l, r)
    }
/*
    // But, this fails.
    def unzip[B, C](_this: MyVector[(B, C)]): (MyVector[B], MyVector[C]) = {
        (_this.map{ bc => bc._1 }, _this.map{ bc => bc._2 })
    }
*/
}
/*
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.scala_tools.maven.executions.MainHelper.runMain(MainHelper.java:151)
        at org.scala_tools.maven.executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.Error: T1 in class Tuple2 cannot be instantiated from ?bc.type
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.throwError$1(Types.scala:3098)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.toInstance$1(Types.scala:3126)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3130)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3003)
        at scala.tools.nsc.symtab.Types$TypeMap.mapOver(Types.scala:2797)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3132)
        at scala.tools.nsc.symtab.Types$Type.asSeenFrom(Types.scala:498)
        at scala.tools.nsc.symtab.Types$Type.memberType(Types.scala:528)
        at scala.tools.nsc.symtab.Types$SingleType.underlying(Types.scala:1077)
        at scala.tools.nsc.symtab.Types$SimpleTypeProxy$class.isHigherKinded(Types.scala:175)
        at scala.tools.nsc.symtab.Types$SingletonType.isHigherKinded(Types.scala:961)
        at scala.tools.nsc.symtab.Types$class.isSubType2(Types.scala:4028)
        at scala.tools.nsc.symtab.Types$class.isSubType0(Types.scala:4012)
        at scala.tools.nsc.symtab.SymbolTable.isSubType0(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$$anonfun$isSubType$1.apply(Types.scala:3919)
        at scala.tools.nsc.symtab.Types$$anonfun$isSubType$1.apply(Types.scala:3907)
        at scala.tools.nsc.symtab.Types$undoLog$.undoUnless(Types.scala:129)
        at scala.tools.nsc.symtab.Types$class.isSubType(Types.scala:3906)
        at scala.tools.nsc.symtab.SymbolTable.isSubType(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$Type.$less$colon$less(Types.scala:599)
        at scala.tools.nsc.symtab.Types$$anonfun$thirdTry$1$3.apply(Types.scala:4128)
        at scala.tools.nsc.symtab.Types$$anonfun$thirdTry$1$3.apply(Types.scala:4128)
        at scala.tools.nsc.symtab.Types$ExistentialType.withTypeVars(Types.scala:1970)
        at scala.tools.nsc.symtab.Types$class.thirdTry$1(Types.scala:4128)
        at scala.tools.nsc.symtab.Types$class.secondTry$1(Types.scala:4092)
        at scala.tools.nsc.symtab.Types$class.firstTry$1(Types.scala:4069)
        at scala.tools.nsc.symtab.Types$class.isSubType2(Types.scala:4195)
        at scala.tools.nsc.symtab.Types$class.isSubType0(Types.scala:4012)
        at scala.tools.nsc.symtab.SymbolTable.isSubType0(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$$anonfun$isSubType$1.apply(Types.scala:3919)
        at scala.tools.nsc.symtab.Types$$anonfun$isSubType$1.apply(Types.scala:3907)
        at scala.tools.nsc.symtab.Types$undoLog$.undoUnless(Types.scala:129)
        at scala.tools.nsc.symtab.Types$class.isSubType(Types.scala:3906)
        at scala.tools.nsc.symtab.SymbolTable.isSubType(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$$anonfun$26.apply(Types.scala:4445)
        at scala.tools.nsc.symtab.Types$$anonfun$26.apply(Types.scala:4445)
        at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:269)
        at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:268)
        at scala.collection.immutable.List.filter(List.scala:45)
        at scala.tools.nsc.symtab.Types$class.elimSub0$1(Types.scala:4445)
        at scala.tools.nsc.symtab.Types$class.elimSub(Types.scala:4448)
        at scala.tools.nsc.symtab.Types$class.lub0$1(Types.scala:4518)
        at scala.tools.nsc.symtab.Types$class.lub(Types.scala:4595)
        at scala.tools.nsc.symtab.SymbolTable.lub(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$class.solveOne$1(Types.scala:4342)
        at scala.tools.nsc.symtab.Types$$anonfun$solve$1.apply(Types.scala:4351)
        at scala.tools.nsc.symtab.Types$$anonfun$solve$1.apply(Types.scala:4350)
        at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.tools.nsc.symtab.Types$class.solve(Types.scala:4350)
        at scala.tools.nsc.symtab.SymbolTable.solve(SymbolTable.scala:13)
        at scala.tools.nsc.typechecker.Infer$class.solvedTypes(Infer.scala:161)
        at scala.tools.nsc.Global$analyzer$.solvedTypes(Global.scala:300)
        at scala.tools.nsc.typechecker.Infer$Inferencer.methTypeArgs(Infer.scala:681)
        at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodInstance(Infer.scala:1245)
        at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:2433)
        at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:3308)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3918)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:2152)
        at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:2418)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$29.apply(Typers.scala:2427)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$29.apply(Typers.scala:2427)
        at scala.Tuple2$Zipped$$anonfun$map$1.apply(Tuple2.scala:57)
        at scala.collection.LinearSeqLike$class.foreach(LinearSeqLike.scala:97)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.Tuple2$Zipped.map(Tuple2.scala:55)
        at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:2427)
        at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:3308)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3918)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4119)
        at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:4206)
        at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:1807)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3736)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4106)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2080)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.collection.immutable.List.loop$1(List.scala:125)
        at scala.collection.immutable.List.mapConserve(List.scala:142)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1493)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1305)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3730)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4106)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2080)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.collection.immutable.List.loop$1(List.scala:125)
        at scala.collection.immutable.List.mapConserve(List.scala:142)
        at scala.collection.immutable.List.loop$1(List.scala:129)
        at scala.collection.immutable.List.mapConserve(List.scala:142)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3723)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4106)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2080)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.collection.immutable.List.loop$1(List.scala:125)
        at scala.collection.immutable.List.mapConserve(List.scala:142)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3723)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4106)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2080)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2146)
        at scala.collection.immutable.List.loop$1(List.scala:125)
        at scala.collection.immutable.List.mapConserve(List.scala:142)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2146)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3723)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4061)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4106)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:83)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:281)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:281)
        at scala.tools.nsc.reporters.Reporter.withSource(Reporter.scala:48)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:281)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:77)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:77)
        at scala.collection.Iterator$class.foreach(Iterator.scala:587)
        at scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:285)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:77)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:749)
        at scala.tools.nsc.Global$Run.compile(Global.scala:839)
        at scala.tools.nsc.Main$.process(Main.scala:109)
        at scala.tools.nsc.Main$.main(Main.scala:123)
        at scala.tools.nsc.Main.main(Main.scala)
        ... 6 more
*/
